### ISSUE TITLE
Update phoenix and ecto.

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#1012]
Update Phoenix to 1.4.0 and Ecto to 3.0.

**Comment by marcoherbst** [comment]
@ijunaid8989 I am removing this.

As far as I can see both updates are still in RC status.

Also, we know, without needing an issue, that we have a policy of trying to keep on the latest versions of all dependencies, frameworks etc.

However, if you have spotted in these RCs specific changes you want to make, in advance, to our codebase and you think they make sensible or important issues, you can add them, well described. 

Otherwise, I'd say we just wait until we get to the release version and then implement as we would in normal course.
