### ISSUE TITLE
Dahua Camera - Snapshot Requests

### ISSUE THREAD

**Issue by WarrenHanna** [evercam/evercam-server#1098]
The way we ask for snapshots causes the camera to deny it, allowing it every 7 seconds, but not smoothly like on Hikvision with CGI enabled:

![Dahua](https://user-images.githubusercontent.com/50405348/57369901-b18ee880-7186-11e9-9955-8cc9373f82ba.JPG)

I have enabled CGI on the NVR/Camera:

![CGI](https://user-images.githubusercontent.com/50405348/57369907-b6ec3300-7186-11e9-9535-1e0727ff51b9.JPG)

Anything we can do to improve that?

**Comment by marcoherbst** [comment]
@azharmalik3  you worked on this. You could add your notes and the current status, please.

**Comment by marcoherbst** [comment]
@azharmalik3  ... update this ticket please

**Comment by azharmalik3** [comment]
Made changes in evercam-server to use asynchronous request for Dahua camera only. System will wait to complete the first request and then send another request to the camera. Made these changes in camera recording module and JPEG streaming module.

Worker code changes for asynchronous request: https://github.com/evercam/evercam-server/pull/1106/files#diff-22bb6fd4f6b71d7b8aa989968e5dca63R136

Streamer code changes: https://github.com/evercam/evercam-server/pull/1106/files#diff-c810a0709fb16e07e11ec24ab04e2e3cR62

After this change errors reduced but still have a few numbers of errors due to connection remain open and our system creates a new connection to camera and retries to get snapshot. Made changes in worker to wait until close connection before sending the next request.

Code changes: https://github.com/evercam/evercam-server/pull/1106/files#diff-c44759bcd669c4e8faf77242d2f5f8b3R226

![image](https://user-images.githubusercontent.com/6176136/60077250-02609d80-9743-11e9-97f8-2441137e273e.png)

**Comment by marcoherbst** [comment]
@azharmalik3 give yourself a pat on the back and close this ticket. Well done.
Also thanks to @WarrenHanna
