### ISSUE TITLE
Rename Evercam-Media to Evercam-Server

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#225]
https://help.github.com/articles/renaming-a-repository/
"operations targeting the previous location will continue to function as if made on the new location"

However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:

**Comment by ijunaid8088** [comment]
As an update: We have renamed it on GH level. But still need to change over Devops anyways its working fine with old repo link as well.

**Comment by ijunaid8088** [comment]
I am not in favour of doing that right now. It includes many directory names, which have been created on media server while the first deploy on the scratch server, including upstart job scripts.

This issue is only valid when we are moving media to somewhere else and then it will create directories and everything with a new name.
