### ISSUE TITLE
Use Emails as (optional) Usernames. Remove first letter restriction.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#248]
Purpose: Simplify Signup.

- [  ]  Username not required and make it (when not specified) = Email
- [  ]  Remove limits on username (e.g. first letter and no @ .... )
- [  ] When user changes their email, then if email=username, also change username
- [  ] When user changes email, then email is no longer confirmed (if it was confirmed).
- [  ] Fixes on Dash & Apps
- [  ] .... more?

It is not necessary to retrospectively convert people on usernames to emails. We may do that later.

**Comment by mosic** [comment]
We already have things in place to partially support this (logging in with an email and password instead of username and password). Right now I don't see anything technical that's stopping us from doing this.

Would this mean that we would prevent existing users from using their username to login / forcing them to switch to using email? That seems a bit rough.

@ in urls is fine, for example Medium uses it for usernames in their urls: https://medium.com/@marcoherbst

**Comment by marcoherbst** [comment]
Great, that settles it for me. I see no reason not to do it. We should have done it in the past. It's another simplification.

**Comment by marcoherbst** [comment]
I am escalating this. Have a think  in case you see any reason it wont work.
Also we have a limitation to say it must start with a letter (not a number). If no one sees a good reason for this, then let's remove this limitation.

**Comment by marcoherbst** [comment]
@azharmalik3  done ?

**Comment by azharmalik3** [comment]
Done.
