### ISSUE TITLE
New user activities endpoint gives request timeout error.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#522]
ref: https://github.com/evercam/evercam-dashboard/issues/1522

**Comment by ijunaid8088** [comment]
The issue seems to be a query which is being sent for a string comparison.. as `name`.. and we don't have any index on that field. Better solution is to add an index for that but anyhow there are other solutions as http://www.rokkincat.com/blog/2015/05/13/postgres-full-text-search-in-ecto

**Comment by ijunaid8088** [comment]
Summary:

In past for each camera we are getting logs with a camer_id on which there is an index with done_at in camera activities table. In case if we may add a user_id and add index to it as well. then In future on user activities like logging in/out or billing. What will be the camera ID will be added in regard of this activity? Because it cannot be null. This will not be a good decision on Architectural level.

I will aggressively like to put a clause to have a separate table dedicated to user activities only. with the same configuration as we have for camera activities.
I dont want to make any such decisions on which the action may done by me, cannot be un-done.

**Comment by marcoherbst** [comment]
That's fine, do it, if you think it's the right thing to do.

Seems to me then that the "User Activities" report will include data from both tables. RIght? You're happy with that?

Everything can be undone, don't worry. :)

**Comment by ijunaid8088** [comment]
Nope I am not happy with that. I was only considering user activities as logging in and out along with some else as well.

getting data for a user from camera activities table will be a mess again. 

Do you think will it be a good idea to add camera_id=0 in case of a user activity regarding logging in and logging out?

**Comment by marcoherbst** [comment]
@ijunaid8989 am I right, the last status of this is that you think one reasonable way to implement this is with the camera-id=0 flag for events that are not camera related.

That sounds to me like a good idea, if you're  happy with this, then let's bring this task into Oct milestone.

**Comment by ijunaid8989** [comment]
@marcoherbst Yeah, that's fine with me.

**Comment by marcoherbst** [comment]
Closing this, it's kind of duplicated in the main User Logging Issue
