### ISSUE TITLE
Q: How to improve the current snapshot recording mechanism?

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-server#55]
Taking snapshots and storing them is one of the core functionality of evercam and many existing feature and to-be-developed feature depend on this.
## Right now, we have the following need:
- Live View in Dashboard is calling Media for every one second which inturn requests the camera for a snapshot and stores these images.
- Camera Workers started when Media starts is polling the camera for snapshots for every 1 second or the set frequency  and stores these images in S3.
- Timelapse - still haven't figured it out but eventually it boils down to accessing snapshot that is already captured by the Camera Workers or some other worker.
- Motion detection - need access to last two snapshots at any point of time to compare.
## Goals
- Do not upload multiple snapshots from the same camera for given a time.
- Do not have multiple interface requesting the camera for a snapshot.
- Do not request the camera for a snapshot when the same is available elsewhere S3 or local cache

(\* Right now we have all the problems mentioned in the goals)
## Proposal
- Decouple the fetching snapshot, S3 uploads  and all things done related to these.
  I think this one big change could potentially benefit us in many ways. 

Camera Workers are concerned with (as of today)

[*note 1]
1. getting snapshots from the camera in the set frequency
2. updating the camera status
3. updating the thumbnail url
4.  updating the concache
5. invalidating the redis cache
6. updating camera_activity table
7. uploading to S3

Getting snapshots from the camera is our heartbeat and uploading to S3 or updating the database records are one of the many things that we want to do with the snapshots.

**So I propose the following workers:**
-  Camera Worker
  Fetch snapshots from the camera in the given frequency and store the result in a key store. Don't do anything else. Let's call this key store camera_snapshot_cache
- S3 Worker
  Constantly check for new entries in camera_snapshot_cache and upload it to S3 
- Motion Detection Worker
  take two images from the camera_snapshot_cache in sequence and compare
- DB Worker
  (this is going to be the biggest change and could attract more discussion. Read through carefully.)

We update the following tables currently
1. Camera - Change the status to online or offline
2. Camera - Update the thumbnail url
3. CameraActivity - Logs when the camera went offline or came back online.
4. Snapshot - Create a record for each snapshot recorded

I would like to see how many of the above we could TOTALLY AVOID doing at all.

>  Camera - Change the status to online or offline

When do we really care to know if a camera is offline or online? 
If the answer is when I view the dashboard, can we do this by checking the recent status in camera_snapshot_cache updated by Camera Worker and reply? This could potentially save thousands of calls to db that just updates the status.

>  Camera - Update the thumbnail url

(Again from the perspective of when we need to know this url)
This update is too much on the database while we don't make use of those frequent updates as much. Since the thumbnail urls can be created at any point of time from the camera_exid, we can remove this call and dynamically create a thumbnail url on the fly.

>  CameraActivity - Logs when the camera went offline or came back online.

Right now, if we don't get a snapshot we mark the camera offline but the actual reason could be any of these
- Camera is really offline (owner switched it off)
- Camera is busy
- Network congestion on evercam media server

If the logs just needs to be temporarily maintained, it can also be retrieved from the cache and not hit the database. But if for any legal reasons, this needs to be maintained, then this deserves to be stored in the database.

>  Snapshot 

May be I am insane, can we entirely do away with this table? Can not S3 itself serve as a 'snapshot' table we have now? API makes query to postgres db for the snapshots and gives the list of just snapshot file names. 

if we store the snapshots in s3 buckets, in the format `cameras_id/YYYY/MM/DD/HH` then it should be possible to query the S3 using S3's `prefix` and `delimiter` function and get a list of snapshots for a given timestamp or a period.

What else do we store in `snapshots` table? We store something 'Notes' but don't see any use of it. Still, if we need to store something along side the recorded snapshot, use S3 object meta data.

All this boils down to:
http://martinfowler.com/bliki/TwoHardThings.html

How do we purge `camera_snapshot_cache`? Difficult but still doable.

@mosic I would like to discuss with you on the step [*note 1] and know the implications of modifying these steps in any other part of the system.

cc @marcoherbst

**Comment by mosic** [comment]
Nice writeup @shankardevy, well done. We've gone over most of the things on Skype but I thought I'd also respond to some points here.

I noticed that you haven't mentioned incoming requests processed by the controllers, how would they be affected by this?

>> Camera - Change the status to online or offline

> When do we really care to know if a camera is offline or online? 
If the answer is when I view the dashboard, can we do this by checking the recent status in camera_snapshot_cache updated by Camera Worker and reply? This could potentially save thousands of calls to db that just updates the status.

Camera status is updated only when it's changed, so there shouldn't be too many unnecessary calls to the database currently. The big issue here is how we determine if a camera is online or not, right now the mechanism is pretty simple - if we get a successful image or text response, camera is online, otherwise it is not.

>> Camera - Update the thumbnail url

>(Again from the perspective of when we need to know this url)
>This update is too much on the database while we don't make use of those frequent updates as much. Since the thumbnail urls can be created at any point of time from the camera_exid, we can remove this call and dynamically create a thumbnail url on the fly.

This is a bit trickier than it sounds. Thumbnail url needs to be link to up-to-date, resized version of the last (or recent) snapshot, which is only accessible to users who have that exact url. Currently first and third conditions are fulfilled, but it's not resized. We also need to provide even smaller version (toenail url).

>> CameraActivity - Logs when the camera went offline or came back online.

>Right now, if we don't get a snapshot we mark the camera offline but the actual reason could be any of these
>
>Camera is really offline (owner switched it off)
>Camera is busy
>Network congestion on evercam media server
>If the logs just needs to be temporarily maintained, it can also be retrieved from the cache and not hit the database. But if for any legal reasons, this needs to be maintained, then this deserves to be stored in the database.

If you mention the logs to Marco you'll always get the same response - more logging :) This is one case where we should look at places where it would be useful to add more logging of changes/activities, not removing them.

>> Snapshot

> May be I am insane, can we entirely do away with this table? Can not S3 itself serve as a 'snapshot' table we have now? API makes query to postgres db for the snapshots and gives the list of just snapshot file names.

I know the feeling :) There are two things that aren't obvious here that should be taken in consideration before making bold steps:

* it would probably be cost prohibitive to use S3 LIST requests just for getting the count of snapshots for every period
* there is more data that we need to store in snapshots table. Notes is used mainly to know the source of the snapshot (e.g. Timelapse app), we have begun storing motion detection data for every snapshot, etc.

Now a question back at you, this issue seems to be really focused on optimizing the database operations, and I'm not clear why. The database isn't a bottleneck in any way right now and we're getting a good performance out of it. Have you noticed something about it when testing that lead you to this?

**Comment by shankardevy** [comment]
Thanks @mosic for your valuable feedback.  I will take sometime to digest it. 

What is your thought on decoupling workers for fetching snapshots, uploading it to s3 and updating db retaining the all the existing db updates as it's now? I would love to hear your comments on this.

**Comment by marcoherbst** [comment]
Thumbnails:
We have a lot of flexibility about how these guys are implemented. Don't
let them be part of the problem. Could lambda post processing be a solution?

#Snapshots count:
If this is the stat that is causing us trouble, we can just get rid of it,
with joy.

Snapshot meta data - I think this is important. Maybe it could be saved
entirely separately though. That would certainly be nicer when it comes to
switching from jpeg recordings to rtsp.

Overall, nice.

M



On 15 September 2015 at 04:36, Shankar Dhanasekaran <
notifications@github.com> wrote:

> Thanks @mosic <https://github.com/mosic> for your valuable feedback. I
> will take sometime to digest it.
>
> What is your thought on decoupling workers for fetching snapshots,
> uploading it to s3 and updating db retaining the all the existing db
> updates as it's now? I would love to hear your comments on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/55#issuecomment-140270253>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by jgarciasacristan** [comment]
Is it possible to use one simple ONVIF call to check if the camera if online? Here are all the ONVIF operations. http://www.onvif.org/onvif/ver20/util/operationIndex.html Even asking for the Date and Time will tell us that the camera is alive. Just my 2 cents.

**Comment by shankardevy** [comment]
@jgarciasacristan intersting info with ONVIF. Is it supported by all camera? ONVIF is completely new for me. Is there a dummies guide to ONVIF somewhere? ;-)

**Comment by shankardevy** [comment]
@mosic I would be interested to hear your thoughts before I start working on decoupling the workers. I will be back to work on this next week and it would be great to have your thoughts on this before that.

**Comment by jgarciasacristan** [comment]
@shankardevy  Not sure if it is supported by all cameras, but I suppose most cameras of the market now support some ONVIF commands.  There is plenty of information in the internet about ONVIF. For the evercam-media implementation take a look at lib/onvif and web/controllers/onvif*.ex  directories. 
A quick test is to invoke the API GET cameras/{id}/macaddr and see if it returns an address.

**Comment by marcoherbst** [comment]
@shankardevy

OnVif is partially supported by many cameras. That's about as true a
sentence as we're able to say right now. Sooner or later you or Milos will
write a script to query the mac endpoint on all cameras and we will learn
all sorts of wonderful things.

@jgarciasacristan s idea is perfectly good and there are multiple other
ways, but, for now, we've deliberately chosen to ask for a jpeg every
minute as the minimum requirement to know if a camera is online. It's not
essential to do this, although it has turned out to be extremely helpful
for our timelapses as a backup plan. However, I don't think we're trying to
get rid of this particular problem right now, are we? The way I see it, we
should have a system that is easily capable of collecting 1/min ....

We could reconsider this if there's a good reason to, but right now we're
not worried about the bandwidth implications on the camera side and I like
to think that it is a technical challenge that the system should be able to
handle.

M


On 15 September 2015 at 14:20, jgarciasacristan <notifications@github.com>
wrote:

> @shankardevy <https://github.com/shankardevy> Not sure if it is supported
> by all cameras, but I suppose most cameras of the market now support some
> ONVIF commands. There is plenty of information in the internet about ONVIF.
> For the evercam-media implementation take a look at lib/onvif and
> web/controllers/onvif*.ex directories.
> A quick test is to invoke the API GET cameras/{id}/macaddr and see if it
> returns an address.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/55#issuecomment-140389337>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@jgarciasacristan This was a good idea, today I've ran a script to get a mac address for all cameras and it turns out that only a small amount support ONVIF (my rough guess is less than 25%). So we couldn't use this to rely on anything important at this point, only as an additional features.

**Comment by mosic** [comment]
@shankardevy Decoupling workers sounds like a good idea, but I'd love to see a pseudo-code of it before it's implemented if possible.

One very important thing to have in mind is passing the data across processes, it can easily lead to a memory leak. Example:

1.) Process X is spawned, gets an image from the camera, does some processing, uploads it and is finished - it dies, freeing up the memory. Everything is okay.
2.) Process X is spawned, gets an image from the camera, passes it a new process Y. Process Y does processing, uploads it and dies, along with Process X. In this case the binary data for the image is still kept in memory, causing a memory leak. In our case, a pretty fast one.

This is a known limitation of BEAM, I learned it the hard (and slow) way - by doing what's described in the second example.

**Comment by shankardevy** [comment]
@mosic thanks for your inputs. I don't have a pseudo-code ready to share. However, let me try to explain the steps that I would like to take.

Decouple the camera workers using GenServer and use GenEvent to trigger event notification on various events related to snapshot fetching. This would mean we have the camera workers fetching snapshots and generating various events in the process. Then we could have other workers like S3, DB updater, Timelapse etc which listen on the events from the Snapshot worker and do their job. I visualize a modular code where any new service that depends on the snapshot events be pluggable when it adheres to doing actions based on the event trigger from GenEvent.

**Comment by marcoherbst** [comment]
This is out of date, but a useful reference.
