### ISSUE TITLE
Monitoring Setup

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#613]
- [x] Hetzner Monitoring to devs@ for ALL servers
- [x] Nagios on all RAID to devs@ ....
- [x] Investigate HDD Error monitoring 
- [x] Evercam Media Custom Error Alert to send devs@ email if too many Seaweed timeout errors.

As per call on 19th Jan

**Comment by ijunaid8088** [comment]
We discussed in Daily stand up and instead of doing the last alert in evercam-server..
I have added this thing in Sumo logic to run the seaweedFS save timeout error search to run every 15 minutes and give results for last 15 minutes only when errors will be greater than 50 in count.

Its done and am closing the issue now.
