### ISSUE TITLE
Update Ubuntu & Separate Media & Seaweed Servers

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#688]

**Comment by marcoherbst** [comment]
@ijunaid8989 (or azhar?) what's the specific issue here?

**Comment by ijunaid8989** [comment]
I think the upstart job to Service Unit only as the Stagging server is already running on 16.04.

**Comment by ijunaid8989** [comment]
Addition to the last comment:

For start and stop evercam server we are using upstart jobs, in Ubuntu 14.04. And On the higher versions, the upstart jobs are being replaced by SystemD services, (Service Unit).

On stagging server we are on 16.04 version of ubuntu BUT, the server is being started by the handwritten command in terminal, not a Job or service.

We were/are unable to replicate the same Upstart job to SystemD till now.

**Comment by ijunaid8989** [comment]
@azharmalik3 Would you please update here, what hurdles you come across while creating the same upstart job in SystemD... while setting up the stagging server?

**Comment by marcoherbst** [comment]
https://mfeckie.github.io/Phoenix-In-Production-With-Systemd/
https://wiki.ubuntu.com/SystemdForUpstartUsers

**Comment by ijunaid8989** [comment]
Just for the follow-up.

I have finally created the Upstart Job to SystemD job and its working fine on staging server at the moment. there are only a few onther things which need some considerations after that, this task is ready for implementation.

**Comment by ijunaid8989** [comment]
As per discussion we Sir @azharmalik3 , we should move to the latest version of Ubuntu 17.04, instead of 16.04, Also this is a good chance for us to separate the SeaweedFS volume server and evercam server.

As this is task is not going to be done, as Updating the existing system's Ubuntu version to latest version, Because the changes which we will do on the live system cannot be undone. So it's a huge risk, and we are not in favor of doing this directly to the live system.

The better way would be as discussed: To create a new Ubuntu server with its latest version, and Deploy Evercam Server there, with all the new changes of 17.04, i.e upstart job, Postgres update or any other changes which may come along with it. once the new server will start working perfectly fine, we can re-assign the IPs

**Comment by marcoherbst** [comment]
Done on all except Oct Weed Servers.
