### ISSUE TITLE
Why send notes in request?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#712]
Get to the bottom of this:
"
Btw sending notes is important in the call. To make difference between, what you are trying to load. Evecam Proxy. Evercam thumnail , Timelapse.
If we dont give any notes, It loaded what is available. If you know what i mean? "

**Comment by ijunaid8989** [comment]
In addition to the above comments.

If we don't give any notes, It loaded what is available.. while making end point call for a specific timestamp. was not talking about recording TAB.

**Comment by marcoherbst** [comment]
@ijunaid8989 can you try to fix the English on this issue. It currently doesn't make much sense. Voice call if necessary

**Comment by ijunaid8989** [comment]
Why we send notes in requests:

It's obvious we are having images in different directories, with name of its kind, 

for example, when we are looking at images from the camera, it's in recording folder for which we say 'Evercam Proxy' as a not same for

Timelapse and Snapmail.

That's all, that's why we send the notes in the request, there is nothing more or less in this issue to investigate
