### ISSUE TITLE
Oldest snapshot endpoint is not working correctly.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#741]
On click first, it doesn't get the oldest snapshot. For further clarification see these cameras:
ballyguille ptz
bam-dawson-st
Herbst Wicklow cam
Honda Office

**Comment by azharmalik3** [comment]
I have tested oldest snapshot endpoint for all cameras mentioned in the description. It works and gives the oldest image.

@affan00 could you please explain what issues you experienced?

**Comment by azharmalik3** [comment]
@marcoherbst 
Actually, oldest snapshot endpoint worked and gave image but some cameras does not give the oldest image.

Because function gets all directories `(archives, recordings, snapmail, timelapse)` alphabetically and then get the first directory and return the oldest image from that directory. Actually, we don't know which directory contains the oldest image, we just pick the first directory from the list and return the image. If the directory is empty then check next directory.

**Comment by marcoherbst** [comment]
Hmmm.... another way of writing that could be "Yes, it doesn't work, it uses some strange logic and therefore doesn't return the oldest image. It is fixable, but it's not a quick fix, so let's push this into August".

**Comment by azharmalik3** [comment]
It's done.

Now, the system checks all directories (`recordings, time-lapse, snapmail, archive`) and return the oldest image.
