### ISSUE TITLE
Last online time is 1hr earlier than last image time

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#797]
![image](https://user-images.githubusercontent.com/5648894/29764659-ed51617a-8bcf-11e7-9b21-98cc7e3bb927.png)

Spotted by @vinnieq

**Comment by ijunaid8989** [comment]
at first, it seemed to be an issue related to online offline logs, where the last log wasn't being added so, last online time was not updated as well.

But, Actually, the issue was, on the details page, the created_at date and last_online_time were being shown in Etc/UTC format, not in camera time zone, So its fixed now and deployed as well.
