### ISSUE TITLE
Other Storage Issues 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#835]
- [x]  Move .150 to new Server
- [x] Monitor CX Server Compression
- [x] Blog Post about Storage Server Failures & Actions
- [x] Filer Backup (Make a plan)

**Comment by ijunaid8989** [comment]
Follow up:

I have totally diagnosed server 150 for HDD and RAID errors, Everything is fine on it, even after a fresh install on Linux.

There are some other issues which I have listed there. https://docs.google.com/document/d/1Yxhj6AxXd4X1V9womEH96BwAOhPl8fcWFUefFefv5kk/edit

The errors coming in logs are mostly about BIOS issues.

Other than that, 
```
 ipmi_si dmi-ipmi-si.0: The BMC does not support clearing the recv irq bit, compensating, but the BMC needs to be fixed.
```

The above issue is related to some watchdog being enabled from BIOS, due to which server reboots after some specific time.  there is nothing more or less useful in the logs or in `dmesg`.

Monitor CX Server Compression:

As I have stopped the compaction by myself and go through all files to see if any structure of files gets changed, the compaction process changed nothing regarding the speed of `GET` requests, tested it with old and latest version of seaweedfs as well.

All files are in binary format, the difference of size has occurred between old and new files. new LDBs are slightly increased in size. (few bytes). Just to remind: The purpose of compaction was: 

To create a Level after removing corruption ( https://github.com/syndtr/goleveldb/issues/184 ) so that, It will make things work more faster. (A Failed experiment).`

We have clone server 150 to a new server: with Adaptec RAID (in past it was megaRAID).

Now We are cancelling 2 servers, Old 150 server and also the one on which compaction was going on.

**Comment by ijunaid8989** [comment]
pt5: Filer Backup.

As per my suggestion: We should pick the least favourite time for camera recordings
1: Stop seaweedfs
2: Copy Filer Folder to a new server only being used for filer backups
3: Start seaweedfs

This could be done manually but my preference would be to add a background job to run on each weekend to do so, (either in evercam server a mix task or in evercam admin a whenever gem's cron job)

**Comment by ijunaid8989** [comment]
Its done.
