### ISSUE TITLE
Logs showing incorrect data - please fix.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#859]

**Comment by ijunaid8989** [comment]
FYI:

at first, we had a try and catch, in which we were adding the logs for a camera, after updating camera status

```
    try do
      params = construct_camera(datetime, status, camera.is_online == status)
      changeset = Camera.changeset(camera, params)
      camera = Repo.update!(changeset)
      broadcast_change_to_users(camera)
      Camera.invalidate_camera(camera)
    catch _type, error ->
      Util.error_handler(error)
    end
```
I have excluded that part of this try and catch, due to which I am getting a non-updated camera, whom the status was not updated, and eventually it's going to be changed after try and catch phase.

So I am adding the log before its status update:

Snapshot gen-server will tell its "online", to make the status of camera online, but as I am having camera before update, so It will be offline, So every time, when they are opposite to each other, It will add a log according to gen-server (which actually reason for camera status update (online/offline))

But it's not working completely yet. I have given all that I had to solve this problem but still. I am not satisfied with it 100%.

**Comment by marcoherbst** [comment]
@ijunaid8989 any more notes on this? If not, send it to Long Finger. We'll keep an eye on it and, hopefully, at some point it will get a 100% fix.

Write your notes as if you are writing to someone from the future, when you have gone to live on a luxury island and no longer are available to answer such petty details as fixing log files. This new person will be doing the work with a fresh mind, so help them now, if you can. (Then move to long finger, or, if you think it's working well enough, just close it).
