### ISSUE TITLE
Replace Mailgun Elixir Client with something that is being maintained

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#971]
e.g. https://github.com/thoughtbot/bamboo which, I think, can continue to use Mailgun ... it will replace only our wrapper / client.

Not urgent, just to clean things up for us.

**Comment by ijunaid8989** [comment]
I have been working on this and Also relaced mailgun wrapper with bamboo successfully But I stopped the task on email with attachments. Also created an issue for it on bamboo .
https://github.com/thoughtbot/bamboo/issues/430

**Comment by ijunaid8989** [comment]
It seems like https://github.com/swoosh/swoosh has handled the inline attachments already https://github.com/swoosh/swoosh/pull/159

we will replace mailgun wrapper with that now. 

FYI: I had done this work to use bamboo instead of Mailgun https://github.com/evercam/evercam-server/compare/use_bamboo_for_emails?expand=1

**Comment by ijunaid8989** [comment]
Its done.
